[tool.poetry]
name = "pearson"
description = "A simple chatbot that can be trained to answer questions based on a dataset"
authors = ["mjfactor <emjayfactor@gmail.com>"]
homepage = "https://github.com/mjfactor/Mr-Pearson"
source = "https://github.com/mjfactor/Mr-Pearson"